repos:
  - repo: local
    hooks:
      - id: trufflehog-binary
        name: TruffleHog-Binary
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ["pre-commit", "pre-push"]
      - id: trufflehog-docker
        name: TruffleHog-Docker
        description: Detect secrets in your data.
        entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ["manual"]
        #stages: ["pre-commit", "pre-push"]